### ISSUE TITLE
display/filter the type of variant

### ISSUE THREAD

**Issue by vivianTan7** [varapp/varapp-backend-py#4]
Hi there,

It seems that the type of variant(snp, indel) and/or the sub_type(ts, tv, ins, del) is not displayed and cannot be filtered, however those information is stored in gemini database in columns 'type' and 'sub_type', therefore is it possible to add this kind of new feature?  Thanks.

Regards

**Comment by jdelafon** [comment]
It seems rather straightforward, I will do that. Unless you suggest otherwise, it will take the form of a radio button "Variant type: [indel|snp]". I am not sure if the distinction transition/transversion, or even insertion/deletion is too fine-grained for the purpose of filtering. We are trying to keep the interface minimal.

**Comment by jdelafon** [comment]
I released a new version (v1.1.1) with this new SNP/Indel filter. I could add a "subtype" filter later on if it feels necessary.
Do not forget to erase the Redis cache ("redis-cli flushall") every time you [update the application](https://varapp-demo.vital-it.ch/docs/src/deploy/update.html) (it is not yet clear to me how to do this automatically).
Please reopen if you encounter any problem.
You can try this new functionality in the demo version:
![demo](https://cloud.githubusercontent.com/assets/12040845/17932531/c2a0669c-6a10-11e6-8428-58c7fb9e8025.png)
